name: contentful_rich_text
description: Rich Text renderer that parses Contentful Rich Text JSON object and returns a renderable Flutter widget tree
version: 0.1.2

authors: 
- Mike Behnke, github@localpcguy <mike@local-pc-guy.com>
- Jonas Zebari, github@jonas-zebari <jonas.zebari@kumanu.com>
- Kumanu github@kumanu <dev@kumanu.com>

homepage: https://github.com/Kumanu/contentful-rich-text-flutter
issue_tracker: https://github.com/Kumanu/contentful-rich-text-flutter/issues

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  html_unescape: ^2.0.0
  url_launcher: ^6.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

